import {useEffect,useState} from 'react';
import {motion} from 'framer-motion';
import {ArrowRight,Play,Lightbulb} from 'lucide-react';
import {Scene} from './Scene';
import {fmt,type Model} from './model';
export function Note({title,children,tone='green'}:{title:string;children:React.ReactNode;tone?:string}){return <div className={`note ${tone}`}><Lightbulb size={17}/><div><strong>{title}</strong><p>{children}</p></div></div>}
export function SectionTitle({kicker,title,description}:{kicker:string;title:string;description:string}){return <div className="section-title"><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{description}</p></div>}
export function PatchGrid({m,image,selected,onSelect,heat=false,head=0}:{m:Model;image?:string;selected:number;onSelect:(n:number)=>void;heat?:boolean;head?:number}){
 const ph=m.ph,pw=m.pw;const qr=Math.floor(selected/pw),qc=selected%pw;
 let weights=Array.from({length:m.n},(_,i)=>{const r=Math.floor(i/pw),c=i%pw;return Math.exp((1.5*Math.cos((r-qr)*.27+head)+Math.cos((c-qc)*.41)+.5*Math.sin(i*.8+head))/1.4)});const sum=weights.reduce((a,b)=>a+b,0);weights=weights.map(v=>v/sum);const max=Math.max(...weights);
 return <div className="patch-image" style={{aspectRatio:`${pw}/${ph}`}}><Scene image={image}/><svg viewBox={`0 0 ${pw} ${ph}`} className="patch-grid" preserveAspectRatio="none" role="group" aria-label="图像 Patch 网格">{Array.from({length:m.n},(_,i)=><rect key={i} x={i%pw} y={Math.floor(i/pw)} width="1" height="1" stroke={i===selected?'#fff8e4':'#fffaf0'} strokeOpacity={i===selected?1:.55} strokeWidth={i===selected?.085:.013} fill={i===selected?'#ac774c':heat?'#d37541':'transparent'} fillOpacity={i===selected?.5:heat?.1+weights[i]/max*.78:0} className="patch-cell" onClick={()=>onSelect(i)}><title>{`Patch ${i}: row ${Math.floor(i/pw)}, col ${i%pw}${heat?`, mock attention ${(weights[i]*100).toFixed(3)}%`:''}`}</title></rect>)}</svg><span className="image-label">{heat?'MOCK ATTENTION':'RGB + PATCH GRID'}</span></div>
}
export function PatchLab({m,image,selected,onSelect,onTensor,initialStage=0}:{m:Model;image?:string;selected:number;onSelect:(n:number)=>void;onTensor:(id:string)=>void;initialStage?:number}){
 const [stage,setStage]=useState(initialStage);const [animate,setAnimate]=useState(false);const [windowStart,setWindowStart]=useState(0);
 useEffect(()=>{setWindowStart(Math.floor(selected/16)*16)},[selected]);
 useEffect(()=>{onTensor(['patch','tokens','position'][stage])},[stage]);
 useEffect(()=>{if(!animate)return;const timer=setInterval(()=>setStage(s=>{if(s===2){setAnimate(false);return 0}return s+1}),1100);return()=>clearInterval(timer)},[animate]);
 const r=Math.floor(selected/m.pw),c=selected%m.pw;
 return <><SectionTitle kicker="01 / PATCH ↔ TOKEN" title="Patch 与 Token 的双向对应" description="点击格子或 token，查看 row、col 与 token index。"/><div className="two-column"><div><PatchGrid m={m} image={image} selected={selected} onSelect={onSelect}/><div className="caption">{m.ph} × {m.pw} grid · {m.n.toLocaleString()} patches · patch size 14</div></div><div className="token-panel"><div className="panel-heading"><h3>Image Tokens</h3><span className="badge">{fmt([1,m.n,m.dim])}</span></div><p>row <b>{r}</b> · col <b>{c}</b> ↔ <b>token #{selected}</b></p><div className="token-buttons">{Array.from({length:Math.min(16,m.n-windowStart)},(_,i)=>windowStart+i).map(n=><button key={n} className={n===selected?'active':''} onClick={()=>onSelect(n)}><span>t<sub>{n}</sub></span><small>{Array.from({length:4},(_,d)=>Math.sin(n*.7+d*.9).toFixed(1)).join(' · ')}</small></button>)}</div><div className="pagination"><button disabled={windowStart===0} onClick={()=>setWindowStart(Math.max(0,windowStart-16))}>← 前 16 个</button><small>{windowStart}–{Math.min(m.n-1,windowStart+15)} / {m.n}</small><button disabled={windowStart+16>=m.n} onClick={()=>setWindowStart(windowStart+16)}>后 16 个 →</button></div></div></div>
 <div className="experiment-card"><div className="panel-heading"><h3>Patch #{selected} → Embedding</h3><button onClick={()=>{setStage(0);setAnimate(true)}}><Play size={14}/>播放切块与投影</button></div><div className="stage-tabs">{['1 · 14×14×3 Patch','2 · Linear Projection','3 · Position + CLS'].map((s,i)=><button key={s} className={stage===i?'active':''} onClick={()=>{setStage(i);onTensor(['patch','tokens','position'][i])}}>{s}</button>)}</div><div className="patch-transform"><div className="magnified"><svg viewBox={`${c/m.pw*100} ${r/m.ph*100} ${100/m.pw} ${100/m.ph}`}><Scene image={image}/></svg><span>14 × 14 × 3</span></div><ArrowRight/><motion.div className="vector" animate={{opacity:stage>=1?1:.3,y:stage>=1?0:8}}><small>588 数值 → W ∈ ℝ<sup>{m.dim}×588</sup></small><div>{Array.from({length:Math.min(8,m.dim)},(_,d)=><span key={d}>{Math.sin(selected*.7+d*.9).toFixed(2)}</span>)}{m.dim>8&&<span>…</span>}</div><b>{m.dim} 维 feature representation</b><small>向量数值为模拟 · 实际实现为 stride=14 的卷积</small></motion.div></div>{stage===2&&<Note title="空间顺序保留；CLS 单独加入">patch token index = row × {m.pw} + col；添加位置编码与 CLS 后进入 blocks 的 shape 是 {fmt([1,m.n+1,m.dim])}。CLS 没有对应图片格子。</Note>}</div><Note title="每个 token 表示一个 14×14 区域">一个 embedding 是整个 14×14 RGB 区域的特征表示。Transformer 会更新它的内容，但它在序列中的索引仍对应原 patch 位置。</Note></>;
}
export function ReshapeLab({m,selected,onSelect,onTensor}:{m:Model;selected:number;onSelect:(n:number)=>void;onTensor:(id:string)=>void}){
 const [phase,setPhase]=useState(0),[channel,setChannel]=useState(0),[feature,setFeature]=useState(1);
 const startR=Math.min(Math.max(0,Math.floor(selected/m.pw)-1),m.ph-4),startC=Math.min(Math.max(0,selected%m.pw-1),m.pw-4);
 const indices=Array.from({length:16},(_,i)=>(startR+Math.floor(i/4))*m.pw+startC+i%4);
 function next(p:number){setPhase(p);onTensor(`${['f','transpose','reshape'][p]}${feature}`)}
 return <><SectionTitle kicker="03 / REASSEMBLE" title="Transpose → Reshape 动画" description="先交换 N 与 C，再把 N 拆为 Hₚ×Wₚ。动画中的数值为模拟。"/><div className="panel-heading"><div className="segmented">{[1,2,3,4].map(i=><button className={feature===i?'active':''} onClick={()=>{setFeature(i);onTensor(`reshape${i}`)}} key={i}>F{i}</button>)}</div><label>查看 channel <input type="range" min="0" max={m.dim-1} value={channel} onChange={e=>setChannel(+e.target.value)}/> {channel}</label></div><div className="shape-rail">{[fmt([1,m.n,m.dim]),fmt([1,m.dim,m.n]),fmt([1,m.dim,m.ph,m.pw])].map((s,i)=><button key={s} className={phase===i?'active':''} onClick={()=>next(i)}><small>{['TOKEN SEQUENCE','TRANSPOSE · permute','SPATIAL · reshape'][i]}</small><code>{s}</code><ArrowRight size={16}/></button>)}</div><div className="reshape-stage"><div className="reshape-label">{phase===0?'X：每枚 Token 含 C 个特征数':phase===1?`channel ${channel}：取出每枚 Token 的同一个分量`:`channel ${channel}：${m.ph}×${m.pw} feature map`}</div>{indices.map((n,i)=><motion.button layout key={n} className={`flying-token ${n===selected?'selected':''}`} animate={{left:phase<2?28+(i%8)*57:140+(i%4)*76,top:phase<2?95+Math.floor(i/8)*72:55+Math.floor(i/4)*65,width:phase<2?50:66,height:phase<2?52:55,backgroundColor:phase===2?`hsl(${35+feature*12},28%,${75+Math.sin(n+channel)*8}%)`:'#e7dff0'}} transition={{duration:.7,delay:i*.035}} onClick={()=>onSelect(n)}><b>t{n}</b><small>{Math.sin(n*.3+channel*.4+feature).toFixed(2)}</small></motion.button>)}<div className="reshape-footer">{m.n===16?'16 tokens 的完整演示':`展示完整 ${m.ph}×${m.pw} 网格中从 row ${startR}, col ${startC} 开始的 4×4 局部；全张量 shape 见上方。`}</div></div><div className="center-actions"><button onClick={()=>next(0)}>重置</button><button className="primary" onClick={()=>{next(1);setTimeout(()=>next(2),1100)}}><Play size={15}/>播放 Token → 2D</button></div><Note title="四条路径都执行相同重排">F1–F4 的原始 N 和 C 相同。将它们各自 reshape 后，空间仍是 {m.ph}×{m.pw}；只有后面的 resize_layers 才人为建立不同分辨率。</Note></>;
}
