import {useState} from 'react';
import {ArrowRight,Play} from 'lucide-react';
import {motion} from 'framer-motion';
import {architecture,fmt,type Config,type Model,type Tensor} from './model';
import {Note,SectionTitle} from './Labs';
import {Scene} from './Scene';
export function OperationLab({id,m,data,config,image,onTensor}:{id:string;m:Model;data:Record<string,Tensor>;config:Config;image?:string;onTensor:(s:string)=>void}){
 const [rgb,setRgb]=useState([128,174,103]),[mix,setMix]=useState(false);
 if(id==='input'||id==='prep')return <><SectionTitle kicker="00 / PREPROCESSING" title="先让图像符合模型的输入约定。" description="官方预处理保留宽高比，保证模型输入边长是 14 的倍数；随后转换 RGB 值、归一化并调整维度布局。"/><div className="two-column"><div style={{maxWidth:330}}><Scene image={image}/></div><div className="lab-card" style={{marginTop:0}}><h3>原始图片 → Model Input</h3><code>{fmt(data.input.shape)}</code><div className="down-arrow">↓</div><code>{fmt(data.prep.shape)}</code><p>{config.mode==='real'?`scale=max(${config.target}/${m.rawH}, ${config.target}/${m.rawW})；分别按 14 的倍数取整，并确保每条边≥${config.target}。使用 bicubic resize。`:'Teaching 强制缩放为 56×56 小例子；这一步是教学简化，Real 模式才使用官方的 keep_aspect_ratio / lower_bound。'}</p><button onClick={()=>onTensor('prep')}>检查预处理后的 Tensor</button></div></div><div className="lab-card"><h3>一个 RGB 像素的归一化</h3><p>这里是可操作的数值例子，不是从上传图片读取的真实像素。官方读取 BGR 后转换为 RGB，并除以 255。</p><div className="normalization-table">{['R','G','B'].map((ch,i)=><label key={ch}><b>{ch}</b><input type="range" min="0" max="255" value={rgb[i]} onChange={e=>setRgb(arr=>arr.map((v,j)=>i===j?+e.target.value:v))}/><span>{rgb[i]}</span><ArrowRight size={12}/><code>({(rgb[i]/255).toFixed(3)} − {architecture.normalization.mean[i]}) / {architecture.normalization.std[i]} = <strong>{((rgb[i]/255-architecture.normalization.mean[i])/architecture.normalization.std[i]).toFixed(3)}</strong></code></label>)}</div></div><Note title="PrepareForNet 只调整布局">浏览器图像通常是 H×W×RGB；模型使用 B×RGB×H×W。transpose(2,0,1) 后转 float32，再增加 batch 维度；归一化不改变 shape。</Note></>;
 if(!/^(project|resize|scratch)[1-4]$/.test(id)){const tensor=data[id]??data.input;return <><SectionTitle kicker="TENSOR DETAIL" title={tensor.name} description={tensor.meaning}/><div className="lab-card"><code>{fmt(tensor.shape)}</code><p>{tensor.format}</p></div><Note title="这个操作为什么存在">{tensor.why}</Note></>}
 const branch=+(id.match(/(\d)$/)?.[1]??1),kind=id.startsWith('scratch')?'scratch':id.startsWith('resize')?'resize':'project';
 const input=data[kind==='project'?`reshape${branch}`:kind==='resize'?`project${branch}`:`resize${branch}`],output=data[`${kind}${branch}`];
 return <><SectionTitle kicker={`03 / ${kind.toUpperCase()} · BRANCH F${branch}`} title={kind==='resize'?'改变空间尺度，让 ViT Features 成为 Pyramid。':kind==='scratch'?'相加之前，统一 Decoder Channels。':'同一个位置，用新的权重组合 Channels。'} description={output.meaning}/><div className="panel-heading"><div className="segmented">{[1,2,3,4].map(j=><button key={j} className={branch===j?'active':''} onClick={()=>onTensor(`${kind}${j}`)}>F{j}</button>)}</div><button onClick={()=>setMix(!mix)}><Play size={14}/>{mix?'重置':'播放操作'}</button></div><div className="operation-transform"><div><span className="eyebrow">INPUT</span><code>{fmt(input.shape)}</code><div className="channel-stack">{Array.from({length:8},(_,i)=><motion.i key={i} animate={{height:mix?56+i*2:80,backgroundColor:mix?'#d1c3db':'#d7e0c9'}} transition={{duration:.8,delay:i*.05}}/>)}</div><small>{kind==='resize'?'空间变化，channels 不变':`${input.shape[1]} 个输入 channels`}</small></div><ArrowRight size={24}/><div><span className="eyebrow">{kind==='project'?'1×1 CONV':kind==='scratch'?'3×3 CONV':branch===3?'IDENTITY':branch===4?'3×3 CONV · STRIDE 2':'TRANSPOSED CONV'}</span><code>{fmt(output.shape)}</code><div className="channel-stack"><motion.div className="feature-square" animate={{width:mix?(kind==='resize'?[144,110,80,48][branch-1]:100):80,height:mix?(kind==='resize'?[144,110,80,48][branch-1]:100):80}} style={{backgroundColor:'#e2c8ac'}}><div className="square-grid"/></motion.div></div><small>{kind==='resize'?`H×W=${output.shape[2]}×${output.shape[3]}`:`${output.shape[1]} 个输出 channels`}</small></div></div><div className="lab-card"><h3>{kind==='project'?'每个空间位置独立地混合 C 维':kind==='scratch'?'融合需要一致的通道与尺度':'由 kernel / stride / padding 决定输出尺寸'}</h3><p>{kind==='project'?`y[b,c_out,h,w] = Σ W[c_out,c_in]·x[b,c_in,h,w] + bias。1×1 Conv 只混合 channels；不在这一步混合不同空间位置。官方第 ${branch} 路从 C=${m.dim} 调到 Cᵢ=${m.channels[branch-1]}。`:kind==='scratch'?`3×3 Conv 把 Cᵢ=${m.channels[branch-1]} 调到 decoder D=${m.features}，并通过 padding=1 保持空间大小。其他分支也被调成 D，因此能 element-wise Add。`:branch===4?`H_out=floor((H_in+2p−k)/s)+1=floor((${m.ph}+2−3)/2)+1=${Math.ceil(m.ph/2)}；W 同理。奇数网格不能直接假定除以 2 得到整数。`:branch===3?'Identity 原样通过，不增加新尺度变化。':'ConvTranspose 输出 (H_in−1)·stride−2·padding+kernel。这里 kernel=stride，padding=0，因此恰好扩大 4 倍或 2 倍；它使用学习到的权重，不等于普通 bilinear。'}</p></div><Note title="表示层次与空间尺度分开处理">{output.why}</Note></>;
}
