import {useEffect,useState} from 'react';
import {Box,ChevronRight,ChevronLeft,Play,Pause,RotateCcw,Layers,Network,GitBranch,Command,ArrowRight,ExternalLink} from 'lucide-react';
import Lab from './components/Lab';
import Inspector, {type CustomTensor} from './components/Inspector';
import {STEPS,type TensorName} from './lib/content';
import {type Mode,type AttentionKind} from './lib/math';
import {Overview,UNet,Transformer,Comparison,MultiHead} from './components/ModelViews';

type View='overview'|'unet'|'lab'|'transformer'|'comparison'|'heads';
const TITLES:Record<View,string>={overview:'Latent Diffusion',unet:'U-Net 结构',lab:'Attention 计算',transformer:'Transformer Block',comparison:'Self / Cross 对比',heads:'Multi-Head Attention'};
export default function App(){
 const [custom,setCustom]=useState<CustomTensor|null>(null); const inspect=(n:TensorName)=>{setCustom(null);setTensor(n)}; const [view,setView]=useState<View>('overview');const [mode,setMode]=useState<Mode>('teaching');const [step,setStep]=useState(0);const [playing,setPlaying]=useState(false);
 const [selected,setSelected]=useState(2);const [tensor,setTensor]=useState<TensorName>('feature');const [prompt,setPrompt]=useState('a red car on the road');const [draft,setDraft]=useState(prompt);const [kind,setKind]=useState<AttentionKind>('cross');const [multi,setMulti]=useState(false);const [head,setHead]=useState(0);const [residual,setResidual]=useState(true);const [speed,setSpeed]=useState(3500);const [mobileMenu,setMobileMenu]=useState(false);
 const navigate=(v:View)=>{setCustom(null);if(v==='heads')setKind('cross');setView(v);setPlaying(false);setMobileMenu(false);};
 const goStep=(s:number)=>{const next=Math.min(12,Math.max(0,s));setCustom(null);setStep(next);setTensor(kind==='self'&&next===3?'X':STEPS[next].tensor);};
 const changeMode=(m:Mode)=>{setMode(m);setSelected(m==='sd'?335:2);setHead(0);};
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStep(s=>{if(s>=12){setPlaying(false);return s}return s+1}),speed);return()=>clearInterval(timer)},[playing,speed]);
 useEffect(()=>setTensor(kind==='self'&&step===3?'X':STEPS[step].tensor),[step,kind]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName)||view!=='lab')return;if(e.key==='ArrowRight'){e.preventDefault();setPlaying(false);goStep(step+1)}if(e.key==='ArrowLeft'){e.preventDefault();setPlaying(false);goStep(step-1)}if(e.code==='Space'){e.preventDefault();setPlaying(p=>!p)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[view,step]);
 const enterLab=(attention:AttentionKind='cross')=>{setKind(attention);setStep(0);setTensor('feature');navigate('lab');};
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'});},[view,step]);
 const applyPrompt=(e:React.FormEvent)=>{e.preventDefault();setPrompt(draft);};
 const showInspector=view==='lab'||custom!==null;
 return <div className={`app ${view==='lab'?'is-lab':''}`}><header className="topbar"><button className="brand" onClick={()=>navigate('overview')} aria-label="U-Net Attention 首页"><div className="brand-icon"><Box size={23}/></div><span>U-Net <span className="brand-light">Attention</span></span></button>{(view==='lab'||view==='heads')&&<div className="mode-switch" aria-label="模型模式"><button className={mode==='teaching'?'active':''} onClick={()=>changeMode('teaching')}>教学数值 <span>4D</span></button><button className={mode==='sd'?'active':''} onClick={()=>changeMode('sd')}>SD 尺寸 <span>320D</span></button></div>}<button className="mobile-toggle" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="打开导航" aria-expanded={mobileMenu}><Layers size={20}/></button></header>
 <div className={`workspace ${showInspector?'has-inspector':''}`}><aside className={`sidebar ${mobileMenu?'mobile-open':''}`}><div className="sidebar-label">模型与计算</div><nav>{(['overview','unet','lab'] as View[]).map((v,i)=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}>{i===0?<Network size={17}/>:i===1?<Layers size={17}/>:<Box size={17}/>}<span>{TITLES[v]}</span><ChevronRight size={13}/></button>)}</nav>{view==='lab'&&<><div className="sidebar-label steps-label">计算步骤 <span>13</span></div><ol className="step-list">{STEPS.map((s,i)=><li key={i}><button onClick={()=>{navigate('lab');goStep(i)}} className={view==='lab'&&step===i?'current':view==='lab'&&step>i?'complete':''}><span className="step-dot">{String(i+1).padStart(2,'0')}</span><span>{kind==='self'&&i===3?'Image context':s.short}</span>{view==='lab'&&step===i&&<i/>}</button></li>)}</ol></>}<div className="sidebar-label steps-label">结构与对比</div><nav>{(['transformer','comparison','heads'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}>{v==='comparison'?<GitBranch size={16}/>:<Layers size={16}/>}<span>{TITLES[v]}</span></button>)}</nav></aside>
 <main className="main"><div className="breadcrumb"><button onClick={()=>navigate('overview')}>Latent Diffusion</button><ChevronRight size={13}/><span>{TITLES[view]}</span></div>
 {((view==='lab'&&kind==='cross')||view==='heads'||view==='comparison')&&<form className="prompt-bar" onSubmit={applyPrompt}><span className="prompt-label">文本条件</span><input aria-label="Prompt" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="输入文本条件…" maxLength={300}/><button type="submit" title="应用 Prompt" disabled={draft===prompt}>应用 <ArrowRight size={14}/></button><button type="button" className="example-button" onClick={()=>{const p=prompt.includes('red')?'a blue dog on the grass':'a red car on the road';setDraft(p);setPrompt(p)}}>切换示例 ↻</button></form>}
 {view==='lab'&&<div className="lab-options"><div className="segmented"><button className={kind==='cross'?'active':''} onClick={()=>setKind('cross')}>Cross Attention</button><button className={kind==='self'?'active':''} onClick={()=>setKind('self')}>Self Attention</button></div><button className={`small-option ${multi?'active':''}`} onClick={()=>{setMulti(!multi);setHead(0)}}><GitBranch size={14}/>{multi?`${mode==='sd'?8:2} Heads`:'Single Head'}</button>{multi&&<select aria-label="当前 Head" value={head} onChange={e=>setHead(Number(e.target.value))}>{Array.from({length:mode==='sd'?8:2},(_,i)=><option key={i} value={i}>Head {i+1}</option>)}</select>}<span className="numeric-notice">{mode==='sd'?'4D 示例数值 · SD 尺寸单独展示':multi?'实际 2 头计算 · 每头 2 维':'4 维教学计算'}</span></div>}
 {view==='lab'?<Lab step={step} mode={mode} kind={kind} prompt={prompt} selected={selected} onSelect={setSelected} onInspect={inspect} multi={multi} head={head} residual={residual} onResidual={()=>setResidual(!residual)}/>:view==='overview'?<Overview onUNet={()=>navigate('unet')} onLab={(s=0)=>{enterLab();goStep(s)}} onSpec={setCustom}/>:view==='unet'?<UNet onAttention={()=>enterLab()} onSpec={setCustom}/>:view==='transformer'?<Transformer onAttention={enterLab} onSpec={setCustom}/>:view==='comparison'?<Comparison prompt={prompt} onAttention={enterLab} onSpec={setCustom}/>:<MultiHead mode={mode} prompt={prompt} selected={selected} head={head} onHead={setHead} onLab={()=>{setKind('cross');setMulti(true);navigate('lab');goStep(6)}} onSpec={setCustom}/>} 
 <footer className="source-footer"><span>教学计算示例</span><a href="https://github.com/CompVis/latent-diffusion/blob/main/ldm/modules/attention.py" target="_blank" rel="noreferrer">CompVis 源码参考 <ExternalLink size={11}/></a></footer></main>
 {showInspector&&<Inspector name={tensor} mode={mode} kind={kind} multi={multi} selected={selected} custom={custom} onClose={view==='lab'?undefined:()=>setCustom(null)}/>}</div>
 {view==='lab'&&<div className="playback"><div className="playback-info"><span className="playback-indicator"/><span>{`${String(step+1).padStart(2,'0')} / 13`}<small>{kind==='self'&&step===3?'Image context':STEPS[step].short}</small></span></div><div className="playback-controls"><button aria-label="Previous" disabled={step===0} onClick={()=>{setPlaying(false);goStep(step-1)}}><ChevronLeft size={16}/> 上一步</button><button className="play-button" onClick={()=>{if(step===12)goStep(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'暂停':'自动播放'}</button><button className="next-button" disabled={step===12} onClick={()=>{setPlaying(false);goStep(step+1)}}>下一步 <ChevronRight size={16}/></button><button className="reset-button" aria-label="Reset" onClick={()=>{setPlaying(false);goStep(0);setSelected(mode==='sd'?335:2);setResidual(true)}}><RotateCcw size={16}/></button></div><div className="speed-control"><select aria-label="播放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={6000}>慢速 · 6s</option><option value={3500}>标准 · 3.5s</option><option value={1600}>快速 · 1.6s</option></select><span><Command size={12}/> ← → / Space</span></div><div className="bottom-progress" style={{width:`${(step+1)/13*100}%`}}/></div>}
 </div>;
}




