import {useId,useState,useEffect,useRef} from 'react';

import type {Matrix} from './engine';
import {fmt} from './engine';
function useColumns(labelWidth:number,cellWidth:number,max:number){
 const ref=useRef<HTMLDivElement>(null),[columns,setColumns]=useState(Math.min(4,max));
 useEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(([entry])=>setColumns(Math.max(1,Math.min(max,Math.floor((entry.contentRect.width-labelWidth-20)/cellWidth)))));observer.observe(ref.current);return()=>observer.disconnect();},[labelWidth,cellWidth,max]);
 return {ref,columns};
}
function ColumnPager({name,total,start,count,setPage}:{name:string;total:number;start:number;count:number;setPage:React.Dispatch<React.SetStateAction<number>>}){
 if(total<=count)return null;
 return <div className="column-pager"><button aria-label={`${name} 上一组列`} disabled={start===0} onClick={()=>setPage(Math.max(0,Math.floor(start/count)-1))}>←</button><span>列 {start+1}–{Math.min(start+count,total)} / {total}</span><button aria-label={`${name} 下一组列`} disabled={start+count>=total} onClick={()=>setPage(Math.floor(start/count)+1)}>→</button></div>;
}
export function MatrixView({name,data,labels,selected=-1,onRow,focused=false,compact=false}:{name:string;data:Matrix;labels?:string[];selected?:number;onRow?:(i:number)=>void;focused?:boolean;compact?:boolean}) {
 const {ref,columns}=useColumns(labels?88:0,compact?48:55,4),[page,setPage]=useState(0),total=data[0]?.length??0,start=Math.max(0,Math.min(page,Math.ceil(total/columns)-1))*columns;
 return <div ref={ref} data-tensor={name} className={`matrix-block ${focused?'tensor-focused':''} ${compact?'compact':''}`}><div className="matrix-title"><strong>{name}</strong><span>{data.length} × {total}</span></div><ColumnPager name={name} total={total} start={start} count={columns} setPage={setPage}/><div className="matrix-scroll"><div className="matrix-bracket">{data.map((r,i)=><div className={`matrix-row ${selected===i?'selected':''}`} key={i} role={onRow?'button':undefined} tabIndex={onRow?0:undefined} aria-label={onRow?`${name} 第 ${i+1} 行`:undefined} onClick={()=>onRow?.(i)} onKeyDown={e=>{if(onRow&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onRow(i);}}}>{labels&&<span className="row-label" title={labels[i]}>{labels[i]}</span>}{r.slice(start,start+columns).map((v,j)=><span key={j} className="matrix-cell" title={`${name}[${i+1}, ${j+start+1}] = ${fmt(v,8)}`} style={{background:`rgba(${v>=0?'170,115,77':'121,137,94'},${Math.min(.26,Math.abs(v)*.12)})`}}>{fmt(v)}</span>)}</div>)}</div></div></div>
}
export function Heatmap({name,data,rows,cols,selected,onSelect,focused=false,small=false}:{name:string;data:Matrix;rows:string[];cols:string[];selected:number;onSelect:(r:number,c:number)=>void;focused?:boolean;small?:boolean}) {
 const finite=data.flat().filter(Number.isFinite),max=Math.max(...finite,1e-6),min=Math.min(...finite,0),{ref,columns}=useColumns(92,58,8),[page,setPage]=useState(0),start=Math.max(0,Math.min(page,Math.ceil(cols.length/columns)-1))*columns;
 return <div ref={ref} data-tensor={name} className={`heatmap ${focused?'tensor-focused':''} ${small?'small':''}`}><div className="matrix-title"><strong>{name}</strong><span>{data.length} × {data[0].length}</span></div><ColumnPager name={name} total={cols.length} start={start} count={columns} setPage={setPage}/><div className="heat-scroll"><table><thead><tr><th>Q ↓ · K →</th>{cols.slice(start,start+columns).map((c,i)=><th key={i} title={c}>{c}</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={i} className={selected===i?'active-row':''}><th>{rows[i]}</th>{r.slice(start,start+columns).map((v,j)=><td key={j}><button className={!Number.isFinite(v)?'masked-cell':''} aria-label={`${rows[i]} → ${cols[j+start]}: ${fmt(v,4)}`} onClick={()=>onSelect(i,j+start)} style={Number.isFinite(v)?{background:`rgba(197,111,74,${.08+.66*(v-min)/(max-min||1)})`}:undefined}>{fmt(v)}</button></td>)}</tr>)}</tbody></table></div><div className="heat-caption"><span>低</span><i/><span>高</span></div></div>
}
export function Diagram({children,height=500,playing=false,label='数据流示意图'}:{children:React.ReactNode;height?:number;playing?:boolean;label?:string}) { const id=useId().replace(/:/g,'');return <svg className={`flow-diagram ${playing?'is-playing':''}`} viewBox={`0 0 920 ${height}`} role="group" aria-label={label}><defs><marker id={`arrow-${id}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker><filter id="soft-glow"><feGaussianBlur stdDeviation="2"/></filter></defs><g style={{'--arrow':`url(#arrow-${id})`} as React.CSSProperties}>{children}</g></svg>}
export function Edge({d,label,x=0,y=0,residual=false,cross=false,active=true,delay=0}:{d:string;label?:string;x?:number;y?:number;residual?:boolean;cross?:boolean;active?:boolean;delay?:number}) {return <g className={`edge ${residual?'residual':''} ${cross?'cross':''} ${active?'active':''}`}><path d={d} markerEnd="var(--arrow)"/><title>{residual?'Residual Connection：此处加回子层原始输入':label||'Tensor 数据流'}</title>{label&&<text x={x} y={y}>{label}</text>}{active&&<circle r="4.5" className="flow-dot"><animateMotion dur="2.4s" begin={`${delay}s`} repeatCount="indefinite" path={d}/></circle>}</g>}
function fitLabel(value:string,width:number,font:number){let used=0,result='';for(const char of value){used+=char.codePointAt(0)!>255?font:font*.56;if(used>width)return result.slice(0,-1)+'…';result+=char;}return result;}
export function Node({x,y,w=240,h=58,title,sub,tone='sand',active=false,onClick}:{x:number;y:number;w?:number;h?:number;title:string;sub?:string;tone?:string;active?:boolean;onClick?:()=>void}) {return <g className={`graph-node ${tone} ${active?'active':''}`} role={onClick?'button':undefined} tabIndex={onClick?0:undefined} aria-label={title} onClick={onClick} onKeyDown={e=>{if(onClick&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onClick();}}}><title>{title}{sub?' · '+sub:''}</title><rect x={x} y={y} width={w} height={h} rx="9"/><circle className="port" cx={x+w/2} cy={y} r="3"/><circle className="port" cx={x+w/2} cy={y+h} r="3"/><text className="node-title" x={x+w/2} y={y+(sub?24:h/2+5)} textAnchor="middle">{fitLabel(title,w-24,16)}</text>{sub&&<text className="node-sub" x={x+w/2} y={y+43} textAnchor="middle">{fitLabel(sub,w-22,12.5)}</text>}{onClick&&<text className="node-expand" x={x+w-18} y={y+20}>↗</text>}</g>}
export function Sum({x,y}:{x:number;y:number}) {return <g className="sum"><circle cx={x} cy={y} r="14"/><text x={x} y={y+5} textAnchor="middle">+</text></g>}
export function OverviewGraph({go,step,playing,gpt,n,t,d,h}:{go:(n:number)=>void;step:number;playing:boolean;gpt:boolean;n:number;t:number;d:number;h:number}) {
 const nx=(x:number)=>gpt?x-240:x;
 return <Diagram height={gpt?1100:1100} playing={playing} label="完整 Transformer：Encoder 输出跨区连接至 Decoder Cross-Attention，残差用虚线表示">
 {!gpt&&<><rect className="group-box encoder-box" x="45" y="342" width="365" height="456" rx="18"/><text className="group-title" x="68" y="373">ENCODER</text><text className="group-tag" x="319" y="373">× 3 layers</text>
 <Node x={96} y={18} title="Input sentence" sub={`${n} tokens · 输入句子`} onClick={()=>go(0)}/><Edge d="M216 76V100" active={step===0}/><Node x={96} y={100} title="Tokenization" sub="text → tokens → token IDs" onClick={()=>go(0)} active={step===0}/><Edge d="M216 158V184" active={step===1}/><Node x={96} y={184} title="Token Embedding" sub={`[1, ${n}, ${d}]`} onClick={()=>go(1)} tone="yellow" active={step===1}/><Edge d="M216 242V294" active={step===2}/><Node x={275} y={265} w={127} h={48} title="Position" tone="green" onClick={()=>go(2)}/><Edge d="M275 289H250Q238 289 238 301V308H230" active={step===2}/><Sum x={216} y={308}/><Edge d="M216 322V396" label={`X · [1, ${n}, ${d}]`} x={230} y={343} active={step===3}/>
 <Node x={96} y={396} title="Multi-Head Self-Attention" sub={`${h} heads · Q, K, V ← X`} tone="coral" onClick={()=>go(3)} active={step>=3&&step<=9}/><Edge d="M216 454V478" active={step===10}/><Edge d="M216 381H70Q58 381 58 393V480Q58 492 70 492H200" residual active={step===10}/><Sum x={216} y={492}/><Edge d="M216 506V523" active={step===11}/><Node x={96} y={523} title="LayerNorm" h={42} tone="brown" onClick={()=>go(11)} active={step===11}/><Edge d="M216 565V599" active={step===12}/><Node x={96} y={599} title="Feed Forward" sub={`${d} → ${d*2} → ${d} · 每个 token 独立`} tone="mauve" onClick={()=>go(12)} active={step===12}/><Edge d="M216 657V675" active={step===13}/><Edge d="M216 580H70Q58 580 58 592V677Q58 689 70 689H200" residual active={step===13}/><Sum x={216} y={689}/><Edge d="M216 703V722" active={step===13}/><Node x={96} y={722} title="LayerNorm" h={42} tone="brown" onClick={()=>go(13)} active={step===13}/><Edge d="M216 764V834" active={step===14}/><Node x={96} y={834} title="Encoder memory" sub={`H · [1, ${n}, ${d}]`} tone="green" onClick={()=>go(14)} active={step===14}/>
 <Edge d="M336 863H430Q454 863 454 839V629Q454 611 477 611H550" cross label="H → K, V" x={457} y={730} active={step===18}/></>}
 <rect className="group-box decoder-box" x={nx(502)} y={342} width="365" height={gpt?439:580} rx="18"/><text className="group-title" x={nx(524)} y="373">{gpt?'DECODER-ONLY':'DECODER'}</text><text className="group-tag" x={nx(789)} y="373">1 layer</text>
 <Node x={nx(550)} y={18} title="Target prefix" sub={`${t} tokens · 已知前缀 / 右移目标`} onClick={()=>go(15)} tone="sand"/><Edge d={`M${nx(670)} 76V184`} active={step===15}/><Node x={nx(550)} y={184} title="Token Embedding" sub={`[1, ${t}, ${d}]`} tone="yellow" onClick={()=>go(15)} active={step===15}/><Edge d={`M${nx(670)} 242V294`} active={step===15}/><Node x={nx(729)} y={265} w={127} h={48} title="Position" tone="green" onClick={()=>go(15)}/><Edge d={`M${nx(729)} 289H${nx(704)}Q${nx(692)} 289 ${nx(692)} 301V308H${nx(684)}`} active={step===15}/><Sum x={nx(670)} y={308}/><Edge d={`M${nx(670)} 322V396`} active={step===16}/>
 <Node x={nx(550)} y={396} title="Masked Self-Attention" sub="Q, K, V ← target prefix" tone="coral" onClick={()=>go(16)} active={step===16}/><Edge d={`M${nx(670)} 454V478`} active={step===17}/><Edge d={`M${nx(670)} 381H${nx(838)}Q${nx(850)} 381 ${nx(850)} 393V480Q${nx(850)} 492 ${nx(838)} 492H${nx(686)}`} residual active={step===17}/><Sum x={nx(670)} y={492}/><Edge d={`M${nx(670)} 506V523`} active={step===17}/><Node x={nx(550)} y={523} title="LayerNorm" h={42} tone="brown" onClick={()=>go(17)} active={step===17}/>
 {!gpt&&<><Edge d="M670 565V584" label="Q" x={685} y={580} active={step===18}/><Node x={550} y={584} title="Cross-Attention" sub="Q ← Decoder · K, V ← Encoder" tone="coral" onClick={()=>go(18)} active={step===18}/><Edge d="M670 642V662" active={step===19}/><Edge d="M670 574H838Q850 574 850 586V664Q850 676 838 676H686" residual active={step===19}/><Sum x={670} y={676}/><Edge d="M670 690V707" active={step===19}/><Node x={550} y={707} title="LayerNorm" h={42} tone="brown" onClick={()=>go(19)} active={step===19}/></>}
 <Edge d={`M${nx(670)} ${gpt?565:749}V${gpt?593:770}`} active={step===20}/><Node x={nx(550)} y={gpt?593:770} title="Feed Forward" h={48} tone="mauve" onClick={()=>go(20)} active={step===20}/><Edge d={`M${nx(670)} ${gpt?641:818}V${gpt?661:838}`} active={step===21}/><Edge d={`M${nx(670)} ${gpt?577:757}H${nx(838)}Q${nx(850)} ${gpt?577:757} ${nx(850)} ${gpt?589:769}V${gpt?663:840}Q${nx(850)} ${gpt?675:852} ${nx(838)} ${gpt?675:852}H${nx(686)}`} residual active={step===21}/><Sum x={nx(670)} y={gpt?675:852}/><Edge d={`M${nx(670)} ${gpt?689:866}V${gpt?706:883}`} active={step===21}/><Node x={nx(550)} y={gpt?706:883} title="LayerNorm" h={32} tone="brown" onClick={()=>go(21)} active={step===21}/><Edge d={`M${nx(670)} ${gpt?738:915}V${gpt?808:957}`} active={step===22}/><Node x={nx(550)} y={gpt?808:957} title="Linear + Softmax" sub={`[1, ${t}, |V|]`} onClick={()=>go(22)} active={step===22}/><Edge d={`M${nx(670)} ${gpt?866:1015}V${gpt?903:1041}`} active={step===23}/><Node x={nx(550)} y={gpt?903:1041} title="Next token prediction" h={42} tone="green" onClick={()=>go(23)} active={step===23}/>
 {gpt&&<text className="diagram-note" x="105" y="1020">GPT 类模型只使用因果 Decoder；此处统一采用 Post-LN 教学排列。</text>}
 </Diagram>
}
export function TokenSelect({tokens,selected,onSelect}:{tokens:string[];selected:number;onSelect:(n:number)=>void}) {return <div className="token-select"><span>追踪 token</span>{tokens.map((t,i)=><button key={i} className={selected===i?'chosen':''} onClick={()=>onSelect(i)}><small>{i}</small>{t}</button>)}</div>}
export function AnimatedSection({children,id}:{children:React.ReactNode;id:string}) {return <div key={id}>{children}</div>}
