export const lessons = [
  ['Tokenization','先把文字变成索引','用一个简化的词级 tokenizer 把句子拆成 token，再映射为词表索引。ID 只是查表地址，不代表语义或大小关系。真实模型通常使用子词 tokenizer。','text → tokens → IDs','input'],
  ['Token Embedding','一个索引，取出一行向量','每个 token ID 从可训练的 Embedding Table 取出一个 d_model 维向量。原始 Transformer 在加入位置编码前将词向量乘以 √d_model。','E = EmbeddingTable[IDs]','input'],
  ['Positional Encoding','让相同的词，拥有不同的位置','自注意力本身不带顺序结构。正弦和余弦位置编码与缩放后的词向量逐元素相加，维度保持不变。关闭位置编码可观察下游结果变化。','X = √d_model · E + PE','input'],
  ['Q / K / V','同一份输入，三种投影','Q：我想找什么？K：我有哪些可匹配的特征？V：被关注时提供什么？这只是直觉类比，语义不是人工指定的。三组线性投影权重在训练中学习。','Q = XWq    K = XWk    V = XWv','attention'],
  ['QKᵀ','每个 Query，和所有 Key 匹配','矩阵的行是 Query，列是 Key。点击一个格子，查看该 token 对的逐维点积。点积是学习得到的匹配分数，不是概率，也不是对语言关系的直接证明。','[L,d_k] × [d_k,L] → [L,L]','attention'],
  ['Scale','先缩放，再分配注意力','特征维度增加时，点积的方差可能变大，使 softmax 过度尖锐、梯度变小。除以 √d_k 可以缓和这种变化。这里 d_k 是一个 Head 的维度。','S = QKᵀ / √d_k','attention'],
  ['Softmax','把匹配分数变成权重','对每一个 Query 的一整行分数做 softmax：每行非负且总和为 1。粗线代表更高的关注权重。数值由当前输入与投影实时算出。','Aᵢⱼ = exp(Sᵢⱼ) / Σⱼ exp(Sᵢⱼ)','attention'],
  ['Weighted Values','关注谁，再从它那里取信息','QKᵀ 决定关注谁，V 决定拿到什么信息。把每个 Value 向量乘以对应权重，再逐元素相加，为当前 token 得到新的特征向量。','Z = A V','attention'],
  ['Multi-Head Attention','用不同的投影，观察不同关系','所有头接收完整输入，分别投影、分别计算注意力，再拼接并通过 Wₒ 混合。下面追踪同一个词在各头中的计算。','d_k = d_model / heads','attention'],
  ['Concat & Wₒ','先拼接，再混合不同的头','沿 feature 维拼接多个 Head 的输出，而不是沿 token 维。随后 Wₒ 线性投影混合这些子空间，输出回到 d_model 维。','MultiHead = Concat(Z₁, …, Zₕ) Wₒ','attention'],
  ['Residual Add','让原始输入有一条直达路径','长弧线保留子层的原始输入 X，在注意力输出之后逐元素加回来。两边 shape 必须一致。残差也为梯度提供直接传播路径。','R = X + MultiHead(X)','encoder'],
  ['LayerNorm','每个 token，独立归一化','沿当前 token 的 feature 维计算均值与方差，再做归一化和可学习的仿射变换。这里 γ = 1、β = 0。不会在不同 token 之间计算均值。','LN(r) = γ ⊙ (r − μ) / √(σ² + ε) + β','encoder'],
  ['Feed Forward','词与词交流之后，变换每个词的特征','同一组 FFN 权重独立作用于每个 token。Linear 扩维 → ReLU → Linear 降维。Attention 混合 token；FFN 混合单个 token 内的 feature。','FFN(x) = ReLU(xW₁ + b₁)W₂ + b₂','encoder'],
  ['Encoder Output','第二次残差与归一化','FFN 的输入绕过 FFN，在输出端再次相加，再做 LayerNorm。这是原始 Transformer 的 Post-LN 排列。输出仍为每个输入 token 保留一个上下文向量。','H = LayerNorm(H₁ + FFN(H₁))','encoder'],
  ['Encoder Stack','形状不变，表示逐层更新','三层 Encoder 使用不同参数。上一层输出作为下一层输入。切换层号可以检查该层的 attention 与输出；最终层的输出作为 Decoder 的 memory。','H⁽ˡ⁺¹⁾ = EncoderBlockˡ(H⁽ˡ⁾)','encoder'],
  ['Decoder Input','先给模型已经知道的前缀','Decoder 输入由 <BOS> 与已知目标 token 构成，也经过 Embedding 与 Position。训练时目标右移：输入 <BOS>, I, love；监督答案 I, love, transformers。','target prefix → Embedding + Position','decoder'],
  ['Causal Mask','未来的位置，不能提前看','第 i 个输入位置可以看自己和以前的位置，预测的是第 i+1 个 token。上三角分数设为 −∞，softmax 后严格为 0。Mask OFF 仅用于观察信息泄漏。','A = softmax(QKᵀ / √d_k + M)','decoder'],
  ['Decoder Add & Norm 1','保留前缀特征，再归一化','Masked Self-Attention 的输入经残差线加到该子层输出，然后按 token 做 LayerNorm。这个结果会产生 Cross-Attention 的 Query。','D₁ = LN(D₀ + MaskedAttention(D₀))','decoder'],
  ['Cross-Attention','带着问题，读取 Encoder 的记忆','Q 由 Decoder 当前特征投影而来，K 与 V 由最终 Encoder 输出分别投影而来。权重矩阵为 [目标长度, 源长度]；源句已经完整可见，因此不加目标侧因果 mask。','Q = D₁Wq    K = HWk    V = HWv','decoder'],
  ['Decoder Add & Norm 2','把读到的信息加入 Decoder','Cross-Attention 输出和它的 Query 输入 D₁ 走残差相加，然后做 LayerNorm。Encoder memory 是 K/V 的来源，不能直接与不同长度的 Decoder 相加。','D₂ = LN(D₁ + CrossAttention(D₁,H))','decoder'],
  ['Decoder FFN','继续加工每个位置的特征','Decoder 的 FFN 与 Encoder 一样按 token 独立计算，但具有自己的参数。其输入包含已知前缀的信息，以及原始架构中从源句读到的信息。','F = ReLU(D₂W₁ + b₁)W₂ + b₂','decoder'],
  ['Decoder Output','最后一条残差，接到输出端','FFN 输入与输出相加并归一化，得到用于词表预测的 Decoder 特征。生成时读取最后一个位置，训练时可以并行计算所有位置的下一 token 分布。','D₃ = LN(D₂ + FFN(D₂))','decoder'],
  ['Linear → Logits','把特征投影到整个词表','每个位置的 d_model 维向量乘以输出权重，得到词表中每个 token 的 logit。生成时只取最后一个位置，再用 softmax 转成概率。','[B,T,d_model] × [d_model,|V|] → [B,T,|V|]','generation'],
  ['逐词生成','读前缀、选词、追加、再计算','读取已知前缀，取 Decoder 输出最后一行，经词表投影与 Softmax 得到下一词分布。选中候选词后，确认追加并进入下一轮；可以逐轮回看。示例使用未训练的固定权重与 8 词小词表，概率可复算，但没有语言生成质量。<EOS> 表示结束。','prefix → probability → append → repeat','generation'],
] as const;
export const chapterNames: Record<string,string>={input:'输入与位置',attention:'Attention 内部',encoder:'Encoder',decoder:'Decoder',generation:'逐词生成'};
