import { useMemo } from 'react';
import {Arrow,Tensor} from './Tensors';
import FeatureMap from './FeatureMap';
import ProjectionStage from './ProjectionStage';
import TextStage from './TextStage';
import AttentionStage from './AttentionStage';
import OutputStage from './OutputStage';
import {tensorSpec} from './Inspector';
import {computeAttention,type Mode,type AttentionKind} from '../lib/math';
import {STEPS,type TensorName} from '../lib/content';

export type LabProps={step:number;mode:Mode;kind:AttentionKind;prompt:string;selected:number;onSelect:(i:number)=>void;onInspect:(n:TensorName)=>void;multi:boolean;head:number;residual:boolean;onResidual:()=>void};
export default function Lab(props:LabProps) {
 const {step,mode,kind,prompt,selected,onSelect,onInspect,multi,head}=props;
 const data=useMemo(()=>computeAttention(prompt,mode,kind,head,multi),[prompt,mode,kind,head,multi]);
 const shape=(name:TensorName)=>tensorSpec(name,mode,kind,multi).shape;
 const base=STEPS[step]; const item=kind==='self'&&[3,4,5].includes(step)?{...base,short:step===3?'Image context':base.short,title:step===3?'Self Attention 的上下文来自 X':step===4?'图像生成 Key':'图像生成 Value',formula:step===3?'Context = X':step===4?'K = X Wk':'V = X Wv',tensor:step===3?'X' as TensorName:base.tensor,explanation:'Self Attention 使用图像 X 作为上下文，不需要编码文本。Q、K、V 来自同一序列，却经过三组不同的学习投影。'}:base;
 return <><div className="page-heading"><div className="eyebrow"><span className="chapter-dot"/> ATTENTION WORKBENCH <span>/ {kind==='cross'?'CROSS':'SELF'} ATTENTION</span></div><h1>看见每一步计算<span className="title-badge">交互实验室</span></h1><p>追踪一个图像位置，观察它如何读取{kind==='cross'?'文本':'图像'}条件。</p></div>
 <div className="step-card"><div className="step-heading"><div><span className="step-number">{String(step+1).padStart(2,'0')} <small>/ 13</small></span><h2>{item.title}</h2></div><span className="step-category">{item.short}</span></div><div className="formula-strip"><code>{item.formula}</code><button onClick={()=>onInspect(item.tensor)}>检查 Tensor ↗</button></div><div className="stage-animated" key={`${step}-${mode}-${kind}`}>{step===0?<div className="stage-content"><Tensor name="feature" shape={shape('feature')} onSelect={onInspect}/><FeatureMap mode={mode} selected={selected} onSelect={onSelect}/></div>:step===1?<div className="stage-content"><div className="reshape-shapes"><Tensor name="feature" shape={shape('feature')} onSelect={onInspect}/><Arrow label="合并 H、W"/><code>[1, {mode==='sd'?320:4}, {mode==='sd'?1024:4}]</code><Arrow label="交换轴"/><Tensor name="X" shape={shape('X')} onSelect={onInspect}/></div><FeatureMap mode={mode} selected={selected} onSelect={onSelect} flatten/><div className="insight"><b>{mode==='sd'?'1024 = 32 × 32':'4 = 2 × 2'}</b><p>{mode==='sd'?'1024 个 image tokens，每个有 320 维特征。':'4 个 image tokens，每个有 4 维特征。'}空间位置被保留，只是重新排列为序列。</p></div></div>:step===2?<ProjectionStage target="Q" data={data} selected={selected} shape={shape} onInspect={onInspect}/>:step===3&&kind==='cross'?<TextStage prompt={prompt} mode={mode} data={data} shape={shape} onInspect={onInspect}/>:step===3?<div className="stage-content"><Tensor name="X" shape={shape('X')} onSelect={onInspect}/><div className="insight"><b>Self Attention 的上下文也是图像</b><p>Q、K、V 都从 X 投影。没有文本 C 参与这一层。每个位置读取其他图像位置的 Value，后续 Cross Attention 再引入文本。</p></div><FeatureMap mode={mode} selected={selected} onSelect={onSelect}/></div>:step===4||step===5?<ProjectionStage target={step===4?'K':'V'} data={data} selected={selected} shape={shape} onInspect={onInspect}/>:step>=6&&step<=8?<AttentionStage step={step} mode={mode} data={data} selected={selected} onSelect={onSelect} onInspect={onInspect} shape={shape}/>:step===11?<div className="stage-content"><div className="reshape-shapes"><Tensor name="projected" shape={shape('projected')} onSelect={onInspect}/><Arrow label="恢复 H、W"/><code>[1, {mode==='sd'?32:2}, {mode==='sd'?32:2}, {mode==='sd'?320:4}]</code><Arrow label="通道到前"/><Tensor name="restored" shape={shape('restored')} onSelect={onInspect}/></div><FeatureMap mode={mode} selected={selected} onSelect={onSelect} restore values={data.projected}/><div className="insight"><b>位置返回原处，向量已经更新</b><p>现在 token #{selected} 的条件更新是 <code>[{data.projected[selected].map(x=>x.toFixed(2)).join(', ')}]</code>。网格亮度仅用于标识位置；上述向量才是实际计算的更新。</p></div></div>:<OutputStage step={step} data={data} selected={selected} onInspect={onInspect} shape={shape} residual={props.residual} onResidual={props.onResidual}/>}</div></div>
 <div className="explanation-block"><span className="micro-label">这一箭头意味着什么？</span><p>{step===7?`数值画布当前 head 有 ${data.q[0].length} 维，点积除以 √${data.q[0].length} = ${data.scale.toFixed(3)}。工程 320 维 / 8 heads 时，每头 40 维，使用 √40。缩放有助于避免 Softmax 过早饱和。`:kind==='self'&&[4,5].includes(step)?`${step===4?'K':'V'} 来自图像 X 的线性投影。与 Cross Attention 相比，改变的是上下文来源，点积、Softmax 和加权求和的计算规则保持一致。`:item.explanation}</p></div></>;
}



