import {useEffect,useState} from 'react';
import {Tensor,Vector,Arrow,MatrixGrid} from './Tensors';
import {add,fmt,WO,type computeAttention} from '../lib/math';
import type {TensorName} from '../lib/content';
type Data=ReturnType<typeof computeAttention>;
export default function OutputStage({step,data,selected,onInspect,shape,residual,onResidual}: {step:number;data:Data;selected:number;onInspect:(n:TensorName)=>void;shape:(n:TensorName)=>string;residual:boolean;onResidual:()=>void}) {
 const [progress,setProgress]=useState(0);const [animating,setAnimating]=useState(false);
 const visible=data.tokens.map((t,i)=>({t,i,w:data.weights[selected][i]})).sort((a,b)=>b.w-a.w).slice(0,6).sort((a,b)=>a.i-b.i);
 useEffect(()=>{setProgress(0);setAnimating(false)},[selected,data]);
 useEffect(()=>{if(!animating)return;const timer=setInterval(()=>setProgress(p=>{if(p>=visible.length){setAnimating(false);return p;}return p+1}),700);return()=>clearInterval(timer)},[animating,visible.length]);
 const partial=Array(data.v[0].length).fill(0).map((_,dim)=>visible.slice(0,progress).reduce((s,{i,w})=>s+w*data.v[i][dim],0));
 if(step===10)return <div className="stage-content"><div className="projection-flow"><div><Tensor name="O" shape={shape('O')} onSelect={onInspect}/><Vector values={data.concatenated[selected]} color="#936522" label="各 head 拼接后的向量"/></div><Arrow/><div className="linear-node"><span>OUTPUT PROJECTION</span><b>Wo</b><code>D → C</code></div><Arrow/><div><Tensor name="projected" shape={shape('projected')} onSelect={onInspect}/><Vector values={data.projected[selected]} color="#936522"/></div></div><MatrixGrid values={WO} selectedRow={-1}/><div className="insight"><b>让每个位置的输出重新具有 C 个通道</b><p>输出投影混合各维信息。它不改变 image tokens 的数量。多头的结果先 Concat，再使用同一个 Wo；不是把各头的权重矩阵相加。</p></div></div>;
 if(step===12)return <div className="stage-content"><div className="residual-flow"><div className={`residual-bypass ${residual?'enabled':''}`}><span>原 feature x · 保留路径</span><svg viewBox="0 0 580 100"><path d="M45 85 V10 H540 V85" fill="none" stroke={residual?'#48602f':'#5b6453'} strokeWidth="2" strokeDasharray={residual?'0':'6 5'}/>{residual&&<circle r="3" fill="#48602f"><animateMotion dur="3s" repeatCount="indefinite" path="M45 85 V10 H540 V85"/></circle>}</svg></div><div className="residual-main"><span className="x-node">x</span><Arrow/><div className="attention-node">Attention 分支<br/><small>简化的 Δx</small></div><Arrow/><button className="plus-node" onClick={onResidual} title="切换 Residual">{residual?'+':'→'}</button><Arrow/><span className="x-node">output</span></div></div><div className="residual-vectors"><Vector values={data.x[selected]} label="原 feature x"/><b>{residual?'+':'忽略 x'}</b><Vector values={data.projected[selected]} color="#936522" label="更新 Δx"/><b>=</b><Vector values={residual?add(data.x[selected],data.projected[selected]):data.projected[selected]} label="当前输出"/></div><button className={`toggle-button ${residual?'active':''}`} onClick={onResidual}><i/>{residual?'Residual 已开启 · 点击关闭':'Residual 已关闭 · 点击开启'}</button><div className="insight"><b>更新后的 feature 继续进入 U-Net</b><p>输出具有 [B,C,H,W] 的相同形状，下一层卷积会利用邻域与通道信息继续计算。文本条件逐层影响噪声预测；采样器反复利用预测去噪。Attention 的某一行本身不是检测器，也不能单独保证生成“red car”。</p></div></div>;
 return <div className="stage-content"><div className="tensor-equation"><Tensor name="weights" shape={shape('weights')} onSelect={onInspect}/><b>×</b><Tensor name="V" shape={shape('V')} onSelect={onInspect}/><b>=</b><Tensor name="O" shape={shape('O')} onSelect={onInspect}/></div><div className="weighted-title"><div><span className="micro-label">IMAGE TOKEN #{selected}</span><h3>把关注比例，变成条件信息</h3></div><button className="secondary-button" onClick={()=>{setProgress(0);setAnimating(true)}}>▶ 演示逐项相加</button></div><div className="weighted-terms">{visible.map(({t,i,w},j)=><div key={i} className={j<progress?'accumulated':''} style={{animationDelay:`${j*.1}s`}}><span>{t}</span><b>{fmt(w)}</b><span>×</span><Vector values={data.v[i]} color="#936522"/><span>=</span><Vector values={data.v[i].map(v=>v*w)} color="#426b4e"/></div>)}</div><div className="accumulator"><span className="micro-label">{animating||progress>0?`已累计 ${progress} / ${visible.length} 项`:'完整加权和 · 全部 context tokens'}</span><Vector values={animating||progress>0?partial:data.output[selected]} color="#936522"/>{data.tokens.length>6&&<small>动画展示前 6 个最大权重项；下方为全部 {data.tokens.length} 项的完整结果。</small>}</div>{data.tokens.length>6&&<Vector values={data.output[selected]} color="#936522" label="完整输出（包含未展示的项）"/>}<div className="insight"><b>Key 决定“匹配谁”，Value 决定“读出什么”</b><p>关注 car 的比例并不是输出本身。模型还要读取 V_car 的内容，与其他 token 的 Value 混合，生成该图像位置的新特征。</p></div></div>;
}
