import {useState} from 'react';
import type {CustomTensor} from './Inspector';
import {Arrow} from './Tensors';
const INFO:Record<string,string>={Input:'输入 zₜ 是 VAE latent，加上时间步 embedding 和文本条件 C。输入 Conv 把 4 通道映射为 320 通道。',ResNet:'ResNet 使用卷积提取空间信息，并通过时间步 embedding 调整特征。多个 ResNet 在实际每个分辨率重复；此图以组为单位展开。',Attention:'Attention 使用 SpatialTransformer：GroupNorm → 1×1 Conv → tokens → Transformer → feature map → 1×1 Conv → 外层残差。',Downsample:'下采样减小 H、W，缩短 token 序列。分辨率变小后，每个 token 汇聚了更大区域的特征。',Upsample:'上采样增大空间尺寸。U-Net 解码路径同时利用同分辨率的 skip feature，恢复较细的空间信息。',Skip:'U-Net 的 Skip Connection 通常按通道拼接 cat([current, skip], dim=1)，再进入 ResNet。它与 Attention 内的 x + Δx 残差是两种不同操作。',Output:'末端归一化/激活和输出 Conv 将通道映射回 4，生成与 zₜ 同尺寸的噪声预测。采样器利用它更新 latent。'};
export default function UNet({onAttention,onSpec}: {onAttention:()=>void;onSpec:(s:CustomTensor)=>void}){
 const [active,setActive]=useState('Attention');
 const show=(label:string,c:number,size:number)=>{setActive(label);onSpec({title:`${label} feature`,dims:[1,c,size,size],meanings:['Batch','Channels','Height','Width'],description:INFO[label]});};
 const sub=(label:string,c:number,size:number,attention=false)=><button className={attention?'attention-subblock':''} onClick={()=>attention?onAttention():show(label,c,size)} title={INFO[label]}>{label}{attention&&<span>进入计算 ↗</span>}</button>;
 const blocks=[{c:320,size:32},{c:640,size:16},{c:1280,size:8}];
 return <><div className="page-heading"><h1>U-Net 中的 Attention</h1><p>三个分辨率的 Down / Up 路径，与中间层的 Attention 都可以继续展开。</p></div><div className="diagram-panel"><div className="panel-heading">U-NET · SD 1.x 风格 <span className="diagram-label">256px 输入示例 · 分组示意</span></div><div className="unet-endpoints"><button onClick={()=>show('Input',4,32)}><span>INPUT</span><b>Latent zₜ</b><code>[1,4,32,32] + t</code></button><Arrow/><button onClick={()=>show('Input',320,32)}><b>Input Conv</b><code>4 → 320</code></button><span className="endpoint-spacer"/><button onClick={()=>show('Output',4,32)}><b>Norm → Output Conv</b><code>320 → 4 · predicted ε</code></button></div><div className="unet-columns"><div className="unet-column-label">ENCODER · DOWN ↓</div><div className="skip-column-label">SKIP FEATURES</div><div className="unet-column-label">DECODER · UP ↑</div>{blocks.map(({c,size},i)=><div className="unet-level" key={i}><section className="unet-block"><div className="unet-block-title"><b>Down Block {i+1}</b><button onClick={()=>show('ResNet',c,size)}><code>{c} × {size} × {size}</code></button></div>{sub('ResNet',c,size)}{sub('Attention',c,size,true)}{sub('Downsample',c,size/2)}<span className="vertical-flow-arrow">↓</span></section><button className="skip-link" onClick={()=>show('Skip',c*2,size)} title={INFO.Skip}><span>concat</span><svg viewBox="0 0 130 20"><path d="M0 10 H124 l-7 -5 m7 5 l-7 5" stroke="#5b6453" strokeWidth="1.5" fill="none"/><circle r="2" fill="#936522"><animateMotion dur="3s" repeatCount="indefinite" path="M0 10 H122"/></circle></svg><small>skip · {size}²</small></button><section className="unet-block"><div className="unet-block-title"><b>Up Block {i+1}</b><button onClick={()=>show('ResNet',c,size)}><code>{c} × {size} × {size}</code></button></div>{sub('ResNet',c,size)}{sub('Attention',c,size,true)}{i>0?sub('Upsample',c,size*2):<span className="no-op">最浅层 → output</span>}<span className="vertical-flow-arrow">↑</span></section></div>)}</div><div className="mid-block"><div className="micro-label">深层 ResNet（4²，无 Attention） → MID BLOCK（4²） → 深层 Up + Upsample</div><div><button onClick={()=>show('ResNet',1280,4)}>ResNet</button><Arrow/><button className="attention-subblock" onClick={onAttention}>Attention ↗</button><Arrow/><button onClick={()=>show('ResNet',1280,4)}>ResNet</button></div><code>[1,1280,4,4]</code></div></div><div className="node-detail"><span className="micro-label">当前结构说明</span><h3>{active}</h3><p>{INFO[active]}</p></div><div className="insight"><b>Skip 是通道拼接；Residual 是同尺寸相加</b><p>每个分辨率内有多个重复的 ResNet/Attention。此图保留数据流与尺寸关系，合并了重复模块和部分 skip。实验室默认采用当前层的 [1,320,32,32]，不是整个 U-Net 只用这一个尺寸。</p></div></>;
}
